name: CI/CD — Deploy Infra & Publish Frontend

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Bootstrap CDK (if first deploy)
        run: |
          npx cdk bootstrap aws://${AWS_ACCOUNT}/${AWS_REGION} \
            --require-approval never

      - name: Deploy CDK stack
        id: cdk_deploy
        run: |
          npx cdk deploy ECV_PROJECT \
            --outputs-file cdk-outputs.json \
            --require-approval never

      - name: Extract CloudFront URL
        id: extract
        run: |
          CF_URL=$(jq -r '.ECV_PROJECT.CloudFrontURL' < cdk-outputs.json)
          echo "CLOUDFRONT_URL=$CF_URL" >> $GITHUB_OUTPUT

      - name: Update Live URL file
        run: |
          echo "[Live Demo]($CLOUDFRONT_URL)" > LIVE_URL.md
        # (Optionally) commit it back so your README can `include` or link it

      - name: Commit and push LIVE_URL.md
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add LIVE_URL.md
          git commit -m "chore: update live URL to $CLOUDFRONT_URL"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
