name: CI/CD — Deploy Infra & Publish Frontend

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Configure AWS CLI (fallback)
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ${{ secrets.AWS_REGION }}
          aws configure set default.output json

          # Also create a named profile for CDK
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} --profile cdk
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} --profile cdk
          aws configure set region ${{ secrets.AWS_REGION }} --profile cdk

      - name: Verify AWS credentials
        run: |
          echo "Testing AWS CLI access..."
          aws sts get-caller-identity
          echo "AWS Region: $AWS_REGION"
          echo "AWS Account: $AWS_ACCOUNT_ID"
          echo "Environment variables:"
          echo "AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:0:10}***"
          echo "AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:0:10}***"
          echo "AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION"

      - name: Deploy CDK stack
        id: cdk_deploy
        run: |
          echo "Deploying CDK stack..."
          export CDK_DEFAULT_ACCOUNT=${AWS_ACCOUNT_ID}
          export CDK_DEFAULT_REGION=${AWS_REGION}
          npx cdk deploy ECvProjectStack \
            --outputs-file cdk-outputs.json \
            --require-approval never
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
          CDK_DEFAULT_ACCOUNT: ${{ secrets.AWS_ACCOUNT_ID }}
          CDK_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

      - name: Extract CloudFront URL
        id: extract
        run: |
          CF_URL=$(jq -r '.ECvProjectStack.CloudFrontURL' < cdk-outputs.json)
          echo "CLOUDFRONT_URL=$CF_URL" >> $GITHUB_OUTPUT

      - name: Update Live URL file
        run: |
          echo "[Live Demo]($CLOUDFRONT_URL)" > LIVE_URL.md
        # (Optionally) commit it back so your README can `include` or link it

      - name: Commit and push LIVE_URL.md
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add LIVE_URL.md
          git commit -m "chore: update live URL to $CLOUDFRONT_URL"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
