# This is a basic workflow to help you get started with Actions

name: Deploy static site to GitHub Pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_and_deploy:
    runs-on: ubuntu-latest

    permissions:
      pages: write   # allow publishing
      id-token: write

    steps:
      # 1. Check out your code
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Copy your `site/` folder into an `output/` directory
      - name: Prepare site content
        run: |
          rm -rf output
          mkdir output
          cp -R site/* output/

      # 3. Upload `output/` as the artifact for Pages
      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: output

  deploy:
    needs: build_and_deploy
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    steps:
      # 4. Deploy the artifact to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
